{
    "id": "",
    "name": "",
    "summary": "",
    "contactPerson": "",
    "contactEmail": "",
    "logo": "",
    "negative": "",
    "entityType": "",
    "sector": "",
    "address": "",
    "country": "",
    "website": "",
    "linkedin": "",
    "facebook": "",
    "twitter": "",
    "instagram": "",
    "youtube": "",
    "solution": "",
    "solutionDescription": "",
    "checkAvailability": "",
    "solutionAvailable": "",
    "solutionType": "",
    "solutionSector": "",
    "solitionApplication": "",
    "solutionAdvantages": "",
    "solutionReferences":"",
    "development": ""
}